# Generated by Django 5.1.1 on 2024-09-13 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet_explanation_type', models.CharField(blank=True, choices=[('검사결과 및 처방', '검사결과 및 처방'), ('예후 및 기대수명', '예후 및 기대수명'), ('관리 및 케어방법', '관리 및 케어방법')], max_length=9, null=True)),
                ('written_date', models.CharField(max_length=100)),
                ('content_summary', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('writer_info', models.CharField(default='***보호자', max_length=100)),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vets.vets')),
            ],
        ),
    ]
