// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOzPlWqmaD_9D6MHxnfBKAv-h-s5KC5RE',
    appId: '1:839230426241:web:6559e919b51cc04b00d180',
    messagingSenderId: '839230426241',
    projectId: 'concrete-flutter',
    authDomain: 'concrete-flutter.firebaseapp.com',
    storageBucket: 'concrete-flutter.appspot.com',
    measurementId: 'G-E95LB7XLFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYFLLwvtST93AX3q6abifEw0Ho_Tbchn4',
    appId: '1:839230426241:android:d420a035a06a91d200d180',
    messagingSenderId: '839230426241',
    projectId: 'concrete-flutter',
    storageBucket: 'concrete-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDlyvTXeGjmDYiiBjNu91VihUzMPJjRZM',
    appId: '1:839230426241:ios:66483e7d6532654c00d180',
    messagingSenderId: '839230426241',
    projectId: 'concrete-flutter',
    storageBucket: 'concrete-flutter.appspot.com',
    androidClientId: '839230426241-4q7sgppmpbvv0dr3p1mfe1tb2bva9o4k.apps.googleusercontent.com',
    iosClientId: '839230426241-71845oqofo45dm8cjsa3io0k96pggcie.apps.googleusercontent.com',
    iosBundleId: 'com.concrete.JaegaebalNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDlyvTXeGjmDYiiBjNu91VihUzMPJjRZM',
    appId: '1:839230426241:ios:66483e7d6532654c00d180',
    messagingSenderId: '839230426241',
    projectId: 'concrete-flutter',
    storageBucket: 'concrete-flutter.appspot.com',
    androidClientId: '839230426241-4q7sgppmpbvv0dr3p1mfe1tb2bva9o4k.apps.googleusercontent.com',
    iosClientId: '839230426241-71845oqofo45dm8cjsa3io0k96pggcie.apps.googleusercontent.com',
    iosBundleId: 'com.concrete.JaegaebalNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOzPlWqmaD_9D6MHxnfBKAv-h-s5KC5RE',
    appId: '1:839230426241:web:90502ef796ff5d7d00d180',
    messagingSenderId: '839230426241',
    projectId: 'concrete-flutter',
    authDomain: 'concrete-flutter.firebaseapp.com',
    storageBucket: 'concrete-flutter.appspot.com',
    measurementId: 'G-P6KEYW6MTP',
  );

}