# Generated by Django 5.1.1 on 2024-09-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet_image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('hospital_name', models.TextField()),
                ('vet_name', models.TextField()),
                ('vet_role', models.TextField()),
                ('main_medical_subjects', models.TextField()),
                ('one_line_review', models.TextField(blank=True, null=True)),
                ('exam_result_explanation', models.TextField(blank=True, null=True)),
                ('prognosis_explanation', models.TextField(blank=True, null=True)),
                ('care_method_explanation', models.TextField(blank=True, null=True)),
                ('heart_disease_diagnosis_metrics', models.CharField(blank=True, max_length=250, null=True)),
                ('heart_disease_stage_medications', models.JSONField(blank=True, null=True)),
                ('prescription_possible', models.TextField(blank=True, null=True)),
                ('education', models.JSONField(blank=True, null=True)),
                ('research_activities', models.TextField(blank=True, null=True)),
                ('teaching_activities', models.TextField(blank=True, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('initial_cost', models.JSONField(blank=True, null=True)),
                ('initial_cost_more', models.JSONField(blank=True, null=True)),
                ('hospital_address', models.TextField(blank=True, null=True)),
                ('parking', models.CharField(max_length=100)),
                ('office_hours', models.JSONField(blank=True, null=True)),
                ('exam_time', models.TextField(blank=True, null=True)),
                ('initial_reservation_wait_time', models.TextField(blank=True, null=True)),
                ('tele_consultation', models.CharField(blank=True, choices=[('가능', '가능'), ('불가능', '불가능'), ('진료 후 가능', '진료 후 가능')], max_length=7, null=True)),
                ('radiologist', models.JSONField(blank=True, null=True)),
                ('key_equipment', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
