# Generated by Django 5.1.1 on 2024-09-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vets',
            name='tele_consultation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
