# Generated by Django 5.1.1 on 2024-09-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0003_alter_vets_vet_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vets',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
    ]
