# Generated by Django 5.1.1 on 2024-09-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VetSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.TextField()),
                ('vet_name', models.TextField()),
                ('main_medical_subjects', models.TextField()),
                ('one_line_review', models.TextField(blank=True, null=True)),
                ('exam_result_explanation', models.TextField(blank=True, null=True)),
                ('prognosis_explanation', models.TextField(blank=True, null=True)),
                ('care_method_explanation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
